"""A question asked instead of an answer: one generation, one sentence.

    AI    I can only ask for your information, not look it up, so could you
          please tell me your first name?
    User  Can you repeat?
    AI    Got it — I'll keep that in mind. Sure — I was asking for your first
          name.

Two generation calls made that turn, and the caller heard the wrong halves of
both.

The turn arrived as answered_with_followup with followup_query "repeat" and
nothing extracted, so the value path in _collect_slot — the only place that
knew what a follow-up was — never ran. The no-extraction path had branches for
WAIT, CORRECTED and AMBIGUOUS and none for a question, so a caller asking to be
repeated was a failed answer: a retry burned, and a RETRY sentence generated by
a model that was never told a question had been asked. It answered anyway
("Sure — I was asking for your first name"), because the utterance was in the
history.

Nothing had claimed the question, so BaseAgent.execute's safety net generated a
SECOND sentence for the same turn. That one WAS told about the question and
answered it — and ended by asking for the first name, which a turn whose
contract is "answer only, Python appends the ask" may not do. The sanitizer
dropped the sentence, the text emptied, and the canned FOLLOWUP_RESPOND
fallback went out in its place, in front of the sentence that had already said
it better.

Three general rules come out of that, and none of them are about first names:

  1. A side question with no value is answered where it is asked — every slot
     pipeline in the codebase collects through _collect_slot, so this holds for
     every agent. Asking is not a failed attempt, so the retry budget is not
     charged (up to MAX_FREE_FOLLOWUP_TURNS, after which a caller who only ever
     asks still reaches a representative).
  2. Whatever sentence a turn generates carries the caller's question —
     _generate_slot_retry_response folds in any question the turn has not
     already claimed, whatever the guard. One turn, one generation.
  3. A sanitized-away sentence never becomes a canned line in front of a real
     one: the net contributes nothing, and where Python appends the ask anyway,
     an "answer + ask" sentence is trimmed at the clause boundary instead of
     dropped whole.
"""

from __future__ import annotations

import pytest

from agent.agents.verification.pipelines import build_identity_pipeline
from agent.core.agent import BaseAgent
from agent.core.constants import MAX_FREE_FOLLOWUP_TURNS
from agent.llm.response_generator import _declarative_lead, _render_payload, sanitize_generated
from agent.llm.schema import EventType, FollowupDisposition, WorkerResult

REPEAT = "Can you repeat?"
ANSWER_AND_ASK = (
    "Of course, I can repeat that — I can only ask for your information, "
    "not look it up, so could you please tell me your first name?"
)


@pytest.fixture
def generation(monkeypatch):
    """Stub LLM 2 and record every call it receives this turn."""
    calls: list[dict] = []

    async def _generate(**kwargs):
        calls.append(kwargs)
        return "Sure — I was asking for your first name."

    monkeypatch.setattr("agent.llm.response_generator.generate_recovery_message", _generate)
    return calls


class _Collector(BaseAgent):
    """The identity pipeline, driven one turn at a time — the real collector
    every slot-collecting agent uses."""

    AGENT_NAME = "verification_agent"

    def __init__(self, result: WorkerResult):
        super().__init__()
        self._result = result
        self._pipeline = build_identity_pipeline(self)

    async def run(self, state):
        if interrupt := await self.run_conversation_guards(state, user_text=REPEAT, result=self._result):
            return interrupt
        collected: dict = {}
        pending = await self._pipeline.collect(
            state, list(state["messages"]), collected, decision=self._result
        )
        return pending or self.ask_member(state, "All set.")


def _asked(query: str | None, **extracted) -> WorkerResult:
    return WorkerResult(
        event_type=EventType.ANSWERED_WITH_FOLLOWUP if query else EventType.ANSWERED,
        followup_disposition=FollowupDisposition.ANSWER if query else FollowupDisposition.NONE,
        followup_query=query,
        extracted=extracted,
        needs_freeform_response=True,
    )


def _state(**over) -> dict:
    return {
        "messages": [
            {"role": "assistant", "content": "Could I start with your first name?"},
            {"role": "user", "content": REPEAT},
        ],
        "slot_attempts": {},
        "ambiguous_counts": {},
        "app_run_id": "test-run",
        "awaiting_slot": "first_name",
        "call_intent": "claim_services",
        **over,
    }


# ── the reported turn ────────────────────────────────────────────────────────


async def test_a_repeat_request_costs_exactly_one_generation(generation):
    await _Collector(_asked(REPEAT)).execute(_state())
    assert len(generation) == 1, "the turn generated a second sentence for the same question"


async def test_the_question_reaches_the_generation_that_answers_it(generation):
    await _Collector(_asked(REPEAT)).execute(_state())
    assert generation[0]["guard"] == "FOLLOWUP_RESPOND"
    assert generation[0]["followup_query"] == REPEAT


async def test_the_payload_still_names_the_slot_being_collected(generation):
    """Nothing was captured, so this is a re-ask turn: the model is told which
    slot to put back, and the prompt has it answer and re-ask in one sentence."""
    await _Collector(_asked(REPEAT)).execute(_state())
    payload = _render_payload(
        slot_name=generation[0]["slot_name"],
        attempt=0,
        guard=generation[0]["guard"],
        last_messages=[],
        extracted_value=generation[0]["extracted_value"],
        followup_query=generation[0]["followup_query"],
    )
    assert "Collecting: first name" in payload
    assert "(nothing —" not in payload


async def test_no_canned_line_lands_in_front_of_the_real_sentence(generation):
    result = await _Collector(_asked(REPEAT)).execute(_state())
    assert "I'll keep that in mind" not in result["messages"]["content"]
    assert result["messages"]["content"].startswith("Sure — I was asking for your first name.")


async def test_the_turn_still_ends_by_asking_for_the_slot(generation):
    """Answering a question and then asking for nothing strands the caller."""
    result = await _Collector(_asked(REPEAT)).execute(_state())
    assert result["messages"]["content"].rstrip().endswith("?")
    assert result["awaiting_slot"] == "first_name"


async def test_asking_a_question_is_not_a_failed_attempt(generation):
    result = await _Collector(_asked(REPEAT)).execute(_state())
    assert result["slot_attempts"].get("first_name", {}).get("attempt_count", 0) == 0


async def test_a_caller_who_only_ever_asks_still_reaches_a_representative(generation):
    """The free turns are not unlimited: once they run out the turn counts as
    the non-answer it is, and the slot's own retry budget escalates."""
    state = _state()
    for _ in range(MAX_FREE_FOLLOWUP_TURNS + 1):
        agent = _Collector(_asked(REPEAT))
        # What the graph does between turns: slot records come back from state.
        agent._slots = {k: BaseAgent._restore_slot(k, v) for k, v in state["slot_attempts"].items()}
        result = await agent.execute(state)
        state = {**state, "slot_attempts": result["slot_attempts"]}
    assert state["slot_attempts"]["first_name"]["attempt_count"] == 1
    assert state["slot_attempts"]["first_name_followup"]["attempt_count"] == MAX_FREE_FOLLOWUP_TURNS + 1


async def test_the_question_does_not_ride_into_the_next_turn(generation):
    agent = _Collector(_asked(REPEAT))
    await agent.execute(_state())
    assert agent.consume_side_question() == {}


async def test_a_plain_non_answer_is_still_a_retry(generation):
    """Nothing here changes what happens when the caller says nothing usable."""
    result = await _Collector(_asked(None)).execute(_state())
    assert result["slot_attempts"]["first_name"]["attempt_count"] == 1
    assert generation[0]["guard"] == "RETRY"


async def test_an_answer_is_untouched_and_costs_nothing(generation):
    result = await _Collector(_asked(None, first_name="Emily")).execute(_state())
    assert result["awaiting_slot"] == "last_name"
    assert generation == []


# ── the general rule: whatever generates, carries the question ───────────────


class _Bare(BaseAgent):
    """An agent that generates its own sentence without threading the question
    through session_context — every hand-written collector in the codebase."""

    AGENT_NAME = "notification_setup_agent"

    def __init__(self, result: WorkerResult):
        super().__init__()
        self._result = result

    async def run(self, state):
        if interrupt := await self.run_conversation_guards(state, user_text=REPEAT, result=self._result):
            return interrupt
        from agent.conversation.context import ConversationContext

        msg = await self._generate_slot_retry_response(
            state,
            "notification_method",
            ConversationContext.from_state(state),
            list(state["messages"]),
            guard="RETRY",
            decision=self._result,
        )
        return self.ask_member(state, msg)


async def test_a_generation_that_was_not_given_the_question_is_given_it(generation):
    await _Bare(_asked(REPEAT)).execute(_state(awaiting_slot="notification_method"))
    assert len(generation) == 1
    assert generation[0]["followup_query"] == REPEAT


async def test_the_net_only_fires_for_turns_that_never_generated(generation):
    """The net is still there for a handler that speaks without generating —
    that is the case it was built for."""

    class _Static(_Bare):
        async def run(self, state):
            await self.run_conversation_guards(state, user_text=REPEAT, result=self._result)
            return self.ask_member(state, "Got it — SMS it is.")

    result = await _Static(_asked(REPEAT)).execute(_state(awaiting_slot="notification_method"))
    assert len(generation) == 1
    assert result["messages"]["content"].endswith("Got it — SMS it is.")


# ── nothing canned goes in front of a real sentence ─────────────────────────


async def test_a_net_sentence_that_sanitizes_away_contributes_nothing(monkeypatch):
    """The net's sentence is only ever prefixed. When it comes back as nothing
    but an ask — which that turn may not make — the turn is better off with
    nothing in front of it than with a fallback the model never generated."""

    async def _only_an_ask(**_kwargs):
        return "Could you please tell me your first name?"

    monkeypatch.setattr("agent.llm.response_generator.generate_recovery_message", _only_an_ask)

    class _Static(_Bare):
        async def run(self, state):
            await self.run_conversation_guards(state, user_text=REPEAT, result=self._result)
            return self.ask_member(state, "Could I start with your first name?")

    result = await _Static(_asked(REPEAT)).execute(_state())
    assert result["messages"]["content"] == "Could I start with your first name?"


# ── an answer and an ask in one sentence keep the answer ────────────────────


def test_the_answer_survives_when_python_appends_the_ask():
    kept = sanitize_generated(ANSWER_AND_ASK, guard="FOLLOWUP_RESPOND", will_append_ask=True)
    assert kept == "Of course, I can repeat that — I can only ask for your information, not look it up."


def test_a_sentence_that_is_only_an_ask_is_still_dropped_whole():
    assert (
        sanitize_generated(
            "Could you please tell me your first name?",
            guard="FOLLOWUP_RESPOND",
            will_append_ask=True,
            allow_empty=True,
        )
        == ""
    )


def test_nothing_is_trimmed_when_no_ask_is_coming():
    """Without an appended ask, keeping the lead would leave the caller with a
    statement and no question — the guard's fallback ends in one, so it wins."""
    out = sanitize_generated(
        "That's something a representative can help with — could I get your email address?",
        guard="OFFTOPIC_AGENT",
        collecting_slot="first_name",
        fallback_text="Let's stay with this — anything else?",
    )
    assert out == "Let's stay with this — anything else?"


@pytest.mark.parametrize(
    "sentence, lead",
    [
        ("Of course — your ZIP on file is 12139, is that right?", "Of course — your ZIP on file is 12139."),
        ("I can help with claims, but could you give me your Member ID?", "I can help with claims."),
        ("Could you tell me your first name?", ""),
        ("Sure thing, what is your member ID?", ""),
        ("I understand, could you tell me your first name, please?", ""),
    ],
)
def test_the_cut_lands_between_the_answer_and_the_ask(sentence, lead):
    assert _declarative_lead(sentence) == lead


def test_an_empty_value_does_not_render_as_a_captured_one():
    """ "Extracted this turn:" with nothing after it reads as "nothing was
    captured" — next to "Collecting: (nothing — this turn's value was
    captured)" that is a contradiction, and it came back as a re-ask."""
    payload = _render_payload(
        slot_name="first_name",
        attempt=0,
        guard="FOLLOWUP_RESPOND",
        last_messages=[],
        extracted_value="",
        followup_query=REPEAT,
    )
    assert "Extracted this turn:" not in payload
    assert "(nothing —" in payload
